/** Phase U1 / F0 — icon wrapper over lucide-react, keyed by metadata `icon`. */
import {
  Activity,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  BarChart3,
  Bell,
  Building2,
  Calculator,
  Calendar,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Columns3,
  CreditCard,
  Download,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderKanban,
  Globe,
  Inbox,
  LayoutDashboard,
  ListChecks,
  ClipboardList,
  LogOut,
  Lock,
  Mail,
  Megaphone,
  Menu,
  MessageSquare,
  Network,
  Package,
  Paperclip,
  Pencil,
  Phone,
  Play,
  Pause,
  Zap,
  Plus,
  Receipt,
  RefreshCw,
  Reply,
  ReplyAll,
  Forward,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Star,
  Archive,
  MailOpen,
  StickyNote,
  Target,
  Ticket,
  Trash2,
  TrendingUp,
  User,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Truck,
  BookOpen,
  Landmark,
  Boxes,
  ArrowLeftRight,
  Store,
  Printer,
  ScanLine,
  Barcode,
  Tags,
  ShoppingCart,
  Minus,
  Square,
  Undo2,
  Copy,
  Check,
  ToggleLeft,
  ToggleRight,
  Database,
  Upload,
  X,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  // metadata entity icons
  building: Building2,
  user: User,
  target: Target,
  check: CheckSquare,
  lead: UserPlus,
  product: Package,
  quote: FileSpreadsheet,
  invoice: FileText,
  payment: CreditCard,
  recurring: RefreshCw,
  wallet: Wallet,
  receipt: Receipt,
  // new entity icons
  note: StickyNote,
  proposal: FileText,
  estimation: Calculator,
  contract: FileSignature,
  order: ClipboardList,
  project: FolderKanban,
  milestone: Flag,
  timesheet: Clock,
  campaign: Megaphone,
  ticket: Ticket,
  employee: User,
  department: Network,
  team: Users,
  // ERP: inventory / purchasing / accounting / branches
  branch: Store,
  dealer: Users,
  warehouse: Warehouse,
  supplier: Truck,
  stock: Boxes,
  transfer: ArrowLeftRight,
  ledger: BookOpen,
  accounting: Landmark,
  journal: BookOpen,
  // barcode / labels / POS
  printer: Printer,
  scan: ScanLine,
  barcode: Barcode,
  label: Tags,
  pos: ShoppingCart,
  cart: ShoppingCart,
  return: Undo2,
  minus: Minus,
  square: Square,
  // app/ui icons
  email: Mail,
  mailOpen: MailOpen,
  reply: Reply,
  replyAll: ReplyAll,
  forward: Forward,
  send: Send,
  star: Star,
  archive: Archive,
  paperclip: Paperclip,
  flag: Flag,
  chat: MessageSquare,
  call: Phone,
  file: Folder,
  social: Share2,
  todo: ListChecks,
  lock: Lock,
  logout: LogOut,
  shield: ShieldCheck,
  pipeline: Columns3,
  trending: TrendingUp,
  inbox: Inbox,
  globe: Globe,
  home: LayoutDashboard,
  search: Search,
  plus: Plus,
  download: Download,
  menu: Menu,
  close: X,
  filter: Filter,
  edit: Pencil,
  trash: Trash2,
  calendar: Calendar,
  activity: Activity,
  play: Play,
  pause: Pause,
  zap: Zap,
  copy: Copy,
  checkmark: Check,
  toggleOn: ToggleRight,
  toggleOff: ToggleLeft,
  database: Database,
  upload: Upload,
  bell: Bell,
  reports: BarChart3,
  finance: Wallet,
  settings: Settings,
  users: Users,
  sort: ArrowUpDown,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
};

export function Icon({ name, className = "h-4 w-4" }: { name: string; className?: string }) {
  const Component = MAP[name] ?? Target;
  return <Component className={className} aria-hidden />;
}
